#!/bin/bash

#Generates a LUT that can be used to find the tile-space increment per display-space
#pixel with an 16x16 tile scaled up to sx pixels.

max=65535
f="$1"

: > $f

#Note: Verilator doesn't mind comments, but Yosys does NOT like them
#echo "#LUT generated by $0" > "$f"
for (( sx=0; sx<255; sx++ )); do
	if [ $sx -eq 0 ]; then
		inc=0; #ignore
	else
		inc=$(($max/$sx+1))
	fi
	if [ $inc -gt 65535 ]; then
		inc=65535
	fi
	printf "%04x\n" $inc >> "$f"
	#Calculate where we'd end up in that situation
	if [ -n "$2" ]; then
#		echo $sx $inc
		echo "scale=3; (($inc*$sx)/($max/16))" | bc
	fi
done


